[package]
name = "tql"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[lib]
name = "tql"
doc = true

[dependencies]
chrono = "0.2"
postgres = { version = "0.10.0", features = ["chrono"] }

[dependencies.tql_macros]
path = "tql_macros"
