[package]
name = "tql_macros"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[lib]
name = "tql_macros"
crate-type = ["dylib"]
doc = true
plugin = true

[dependencies]
clippy = "0.0.29"

[dev-dependencies]
chrono = "0.2"
compiletest_rs = "0.0.11"
postgres = { version = "0.10.2", features = ["chrono"] }

[dev-dependencies.tql]
path = ".."
